sudo: required
dist: trusty
language: node_js
node_js:
  - '18'
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm install

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: aserra@werfen.com
  edge: true
  api_key: $NPM_TOKEN
  on:
    tags: true
