sudo: required
dist: jammy
language: node_js
node_js:
  - '20.18.0'
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
  chrome: stable
env:
  global:
    - NPM_CONFIG_LOGLEVEL=verbose

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm i -g npm@10.8.2 --verbose
  - npm --version

install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org --verbose
  - npm ci --verbose

script:
  - npm run build

before_deploy:
  - echo "//registry.npmjs.org/:_auth = $NPM_TOKEN" > ~/.npmrc
  - npm config set registry https://registry.npmjs.org/

deploy:
  skip_cleanup: true
  provider: npm
  edge: true
  email: aserra@werfen.com
  api_key: $NPM_TOKEN
  access: public
  on:
    tags: true
