sudo: required
dist: jammy
language: node_js
node_js:
  - '20.11.0'
addons:
  apt:
    update: true
    sources:
      - google-chrome
    packages:
      - dpkg
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - npm i -g npm@8.19.4
  - npm --version

install:
  - npm install -g makeshift && makeshift -s @systelab-technologies -r https://registry.npmjs.org
  - npm ci

script:
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: aserra@werfen.com
  edge:
    branch: v2.0.3-beta.4
  api_key: $NPM_TOKEN
  on:
    tags: true
